spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 60000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

rate-limit:
  max-requests-per-minute: 60
  max-requests-per-hour: 1000

logging:
  level:
    com.popov: INFO
    org.hibernate.SQL: DEBUG
