eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

# Feign default configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
    group:
      enabled: true

# Service configurations
services:
  base-url: http://localhost
  instances:
    subscription:
      name: finance-subscription-service
      port: 8082
    user:
      name: finance-user-service
      port: 8083
    payment:
      name: finance-payment-service
      port: 8084
    wallet:
      name: finance-wallet-service
      port: 8086

# Spring configuration
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.popov.*
    producer:
      properties:
        spring.json.add.type.headers: false
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 3

# Resilience4j default configurations
resilience4j:
  circuitbreaker:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 20s
      permittedNumberOfCallsInHalfOpenState: 3
    instances:
      finance-subscription-service:
        baseConfig: default
      finance-user-service:
        baseConfig: default
      finance-payment-service:
        baseConfig: default

  retry:
    default:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
    instances:
      finance-subscription-service:
        baseConfig: default
      finance-user-service:
        baseConfig: default
      finance-payment-service:
        baseConfig: default

# Redis configuration
redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 60000

# Logging configuration
logging:
  level:
    com.popov: DEBUG
