server:
  port: 8083

spring:
  application:
    name: finance-user-service
  jpa:
    hibernate:
      ddl-auto: validate

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      user:
        name: finance-user-service
        url: http://localhost:8083
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      user-service:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

logging:
  level:
    com.popov.common.clients: DEBUG
    com.popov.common.clients.fallback: ERROR
