spring:
  cloud:
    gateway:
      routes:
        - id: finance-auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: finance-wallet-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/wallets/**

logging:
  level:
    com.popov: DEBUG
