spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**

logging:
  level:
    com.popov: WARN
