server:
  port: 9090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

rate-limit:
  max-requests-per-minute: 60
  max-requests-per-hour: 1000
