logging:
  level:
    com.popov: DEBUG

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: finance-auth-service
          uri: "http://localhost:8081/"
        - id: finance-user-service
          uri: "http://localhost:8083/"
        - id: finance-subscription-service
          uri: "http://localhost:8082/"
